{{- if .Values.config.hostFlatcarPackages.persistence.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "nebraska.fullname" . }}-packages
  labels:
    {{- include "nebraska.labels" . | nindent 4 }}
    {{- with .Values.config.hostFlatcarPackages.persistence.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
    {{- with .Values.extraLabels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  annotations:
    {{- with .Values.config.hostFlatcarPackages.persistence.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
    {{- with .Values.extraAnnotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  accessModes: {{ .Values.config.hostFlatcarPackages.persistence.accessModes }}
  resources:
    requests:
      storage: {{ .Values.config.hostFlatcarPackages.persistence.size }}
  {{- if .Values.config.hostFlatcarPackages.persistence.storageClass }}
  storageClassName: {{ .Values.config.hostFlatcarPackages.persistence.storageClass }}
  {{- end }}
{{- end }}
