name: link-checker 
on:
  pull_request:

permissions:
  contents: read

jobs:
  link-check:
    name: Check Links
    runs-on: ubuntu-22.04
    steps:
    - name: Check out code
      uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0

    - name: Check links
      uses: lycheeverse/lychee-action@885c65f3dc543b57c898c8099f4e08c8afd178a2  #v2.6.1
      with:
        fail: true
        lycheeVersion: v0.19.1
        args: --verbose --no-progress './**/*.js' './**/*.ts' './**/*.jsx' './**/*.tsx' './**/*.md' './**/*.mkd' './**/*.mdx' './**/*.mdown' './**/*.mdwn' './**/*.mkdn' './**/*.mkdown' './**/*.markdown' './**/*.html' './**/*.htm' './**/*.txt'

