name: updater
on:
  pull_request:
    paths:
    - 'updater/**'

permissions:
  contents: read

jobs:
  build:
    name: Test updater library
    runs-on: ubuntu-24.04
    steps:
    - name: Check out code
      uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0

    - name: Set up Go 1.23
      uses: actions/setup-go@d35c59abb061a4a6fb18e82ac0862c26744d6ab5 # v5.5.0
      with:
        go-version: 1.23.x
      id: go

    - name: Start postgres dependency
      run: |
        docker compose -f backend/docker-compose.test.yaml up -d postgres

    - name: Test library
      env:
        NEBRASKA_DB_URL: "postgres://postgres:nebraska@127.0.0.1:8001/nebraska_tests?sslmode=disable&connect_timeout=10"
      run: |
        cd updater
        go test -v ./...
